"""Table programs that carry CIF-1 fixtures through compiled implementations.

SPEC-09 9.2 (CONF-01) runs every CIF-1 fixture through generated `.ci` table
programs, and SPEC-09 9.8 (CONF-10) observes compiled programs through
`cint-harness`, which reads a case list of `<module> <function> <typed
arguments>` lines and calls each exported function with a fresh context. A
fault ends an entry (SPEC-01 9.4), so each record is its own call.

For a CIF-1 file of one binary operator form, this writes:

- `conformance/tables/<name>.ci`: one exported function applying the operator
  once to its two parameters;
- `conformance/tables/<name>.cases`: one case line per CIF-1 record, in record
  order, so line n of the case list is record n of the CIF-1 file.

`<name>` is the operation identifier with `.` replaced by `_`. The module name
is `tables.<name>`, taking `conformance/` as the source root (SPEC-04 11; the
root is an assumption, ref/OPEN.md O-6).

Only run-time table programs are written. The constant-expression twin that
SPEC-09 CONF-08 asks for is not, because a fault during constant evaluation
rejects the whole module (ref/OPEN.md O-5).

Usage:
    python gen_tables.py conformance/integer-machine/exh8/add.checked.i8.cif1.jsonl [...] --out conformance/tables/

Python standard library only; no floating point; LF line endings.
"""

import argparse
import hashlib
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import imeval  # noqa: E402

# SPEC-01 4.1 and SPEC-04 3.9: operator spelling per (op, form).
OPERATOR = {
    ("add", "checked"): "+", ("sub", "checked"): "-", ("mul", "checked"): "*",
    ("div", "checked"): "/", ("rem", "checked"): "%",
    ("shl", "checked"): "<<", ("shr", "checked"): ">>",
    ("add", "wrap"): "+%", ("sub", "wrap"): "-%", ("mul", "wrap"): "*%", ("shl", "wrap"): "<<%",
    ("add", "sat"): "+|", ("sub", "sat"): "-|", ("mul", "sat"): "*|",
}

CLAUSE = {
    "add": "SPEC-01 4.1, 4.2", "sub": "SPEC-01 4.1, 4.2", "mul": "SPEC-01 4.1, 4.2",
    "div": "SPEC-01 4.1, 4.4", "rem": "SPEC-01 4.1, 4.4",
    "shl": "SPEC-01 4.1, 4.6", "shr": "SPEC-01 4.1, 4.6",
}


def render(cif_bytes, cif_relpath):
    """Return (program bytes, case-list bytes) for one CIF-1 file of one binary form."""
    recs = [json.loads(line) for line in cif_bytes.decode("utf-8").split("\n") if line]
    if not recs:
        raise ValueError("empty CIF-1 file")
    op_ids = {r["op"] for r in recs}
    if len(op_ids) != 1:
        raise ValueError("a table program covers one operation; found %d" % len(op_ids))
    opid = recs[0]["op"]
    parts = opid.split(".")
    if len(parts) != 3 or (parts[0], parts[1]) not in OPERATOR:
        raise ValueError("not a binary operator form: %s" % opid)
    op, form, t = parts[0], parts[1], parts[2].upper()
    if t not in imeval.TYPES:
        raise ValueError("unknown type in %s" % opid)
    for r in recs:
        if len(r["args"]) != 2 or any(a["t"] != t for a in r["args"]):
            raise ValueError("record %s: expected two %s operands" % (r["id"], t))
    name = opid.replace(".", "_")
    module = "tables." + name
    subset = "cint-core-1 (saturating forms are outside cint-boot-1, SPEC-09 5.3)" \
        if form == "sat" else "cint-boot-1"
    src = "".join([
        "// conformance/tables/%s.ci\n" % name,
        "// generated by conformance/tools/gen_tables.py; do not edit\n",
        "// source: %s\n" % cif_relpath,
        "// source sha256: %s\n" % hashlib.sha256(cif_bytes).hexdigest(),
        "// records: %d\n" % len(recs),
        "// clause: %s; SPEC-09 9.2 (CONF-01), 9.3, 9.8 (CONF-10)\n" % CLAUSE[op],
        "// subset: %s\n" % subset,
        "// cases: tables/%s.cases (line n is record n of the source)\n" % name,
        "export %s %s(%s a, %s b) {\n" % (t, name, t, t),
        "    return a %s b;\n" % OPERATOR[(op, form)],
        "}\n",
    ])
    cases = "".join("%s %s %s %s %s %s\n" % (module, name, t, r["args"][0]["v"], t, r["args"][1]["v"])
                    for r in recs)
    return src.encode("ascii"), cases.encode("ascii")


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("cif", nargs="+")
    p.add_argument("--out", required=True)
    p.add_argument("--root", default="conformance",
                   help="directory that source paths in the header are relative to")
    args = p.parse_args(argv)
    os.makedirs(args.out, exist_ok=True)
    for path in args.cif:
        with open(path, "rb") as fh:
            data = fh.read()
        rel = os.path.relpath(path, args.root).replace(os.sep, "/")
        src, cases = render(data, rel)
        name = json.loads(data.split(b"\n", 1)[0])["op"].replace(".", "_")
        for ext, blob in ((".ci", src), (".cases", cases)):
            out = os.path.join(args.out, name + ext)
            imeval.write_bytes(out, blob)
            print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
